# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/

# Setup
title:            'Chintan Shah'
name:             'Chintan Shah'
#tagline:          ''
description:      'Software Engineer'
#url:              http://chintan-sh.github.io/
# uncomment below line to make blog page default instead of about
# baseurl:
baseurl:          '/about'
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Chintan Shah'
  url:            chintan-sh.github.io
  email:          ''
  github:         'https://github.com/chintan-sh'
  facebook:       ''
  twitter:        'https://twitter.com/c0defella'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/chintan14/'

paginate:         3

version:          2.1.0

github:
  repo:           https://github.com/chintan-sh/chintan-sh.github.io

collections:
  - projects
  - talks

